### ISSUE TITLE
Support ShaderTexture( sampler) as first class shader node in shader graph 

### ISSUE THREAD

**Issue by mikialex** [mikialex/artgl#26]
ShaderTexture is not a shader node, but create texture fetch node. This leads Its impossible fetch texel in shaderFunction directly.  Some ShaderFunction compute need sample texture quite often, but we cant pass sampler object to it. 

We should support ShaderTexture( sampler) as first class shader node in shader graph. This has one majoy issue to solve: If we allow user write texture2D in their shader function, this will affect glsl version switch impl.  Another parser should add to extract texel fetch info in shader source and replace with desired.

**Comment by AngusLang** [comment]
It's that possible? Are you sure that webgl support pass samplerXD/Cube to kernel function as arguments?

**Comment by mikialex** [comment]
Yes I tried, It works
